### ISSUE TITLE
link to formatted registry list

### ISSUE THREAD

**Issue by urbanjost** [fortran-lang/fpm-registry#19]
A few suggestions for minor changes to the "fpm packages" page and this registry README.md ...

It would be nice if this repository had a link to  the [fpm packages](https://fortran-lang.org/packages/fpm)page. 

Note that page seems to be inconsistently sorted. It would be nice if the page were sortable  or selectable by categories as more packages are registered but for now it starts off looking sorted in a case-insensitive manner, but then jumps back. So if the user is supposed to enter their PR in a  (case-insensitive?) order in this TOML file  it seems like the packages page should reflect that.

**Comment by certik** [comment]
Can you please send a PR to update the README with a link?

**Comment by urbanjost** [comment]
I have to get more in the mindset of github. Added PR illustrating what I wanted. As recently new to this myself the first time I read this I was still learning what a tag and PR even were, let alone TOML and fpm(1) and what process should be followed. I felt I was digging around a lot to do something simple. I am even thinking some links to git(1) or github PR instructions might be needed as well or an actual CLI example. It is starting to feel more intuitive how to do this but there was actually a bit of a learning curve the first time and so I would like pages like this to be more expansive as there is some good Fortran out there that a cryptic process would hinder being added. Probably seems simple to someone that has been working on similar projects 
but iI think it needs to assume little or no initial knowledge of anything other than Fortran and basic git(1) myself. Added a PR.

**Comment by certik** [comment]
@urbanjost thank you. You are in a perfect position to improve the documentation to make things more intuitive. It is indeed hard for me, as I've been using Git and GitHub for over 10 years now almost every day. If you see how to improve any docs, please go ahead and submit a PR.
