### ISSUE TITLE
Failure in master?

### ISSUE THREAD

**Issue by certik** [fortran-lang/fpm-registry#22]
I got an email with this link with an error at our CI:

https://github.com/fortran-lang/fpm-registry/runs/1183248590

But I am not quite sure what the cause of it is.

@LKedward, any idea?

**Comment by LKedward** [comment]
I'll take a look

**Comment by LKedward** [comment]
My fault - I didn't pin the commit action to a specific version and there's been [a breaking change](https://github.com/EndBug/add-and-commit/releases).

**Comment by certik** [comment]
Ah cool, thanks for figuring it out!

**Comment by LKedward** [comment]
I believe this is now fixed so I will close.
